import { useState } from 'react'
import SupplierForm from '../components/SupplierForm'
import { createSupplier } from '../api/suppliersApi'

export default function AddSupplierPage() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [duplicate, setDuplicate] = useState(null); const [created, setCreated] = useState(null)
  const save = async (values, allowDuplicate = false) => { setBusy(true); setError(''); try { setCreated(await createSupplier({ ...values, allowDuplicate })); setDuplicate(null) } catch (requestError) { if (requestError.status === 409 && !allowDuplicate) setDuplicate(values); else setError(requestError.message || 'The supplier could not be saved. Please try again.') } finally { setBusy(false) } }
  if (created) return <main className="min-h-screen bg-medzo-light-bg px-4 py-10"><div role="status" className="mx-auto max-w-2xl rounded-2xl border border-green-200 bg-white p-8 text-center shadow-sm"><h1 className="text-2xl font-bold text-[#0a192f]">Supplier added successfully</h1><p className="mt-3 text-medzo-text-light">{created.name} is ready to use for future purchase orders.</p><button onClick={() => setCreated(null)} className="mt-6 rounded-lg border border-medzo-blue px-6 py-3 font-semibold text-medzo-blue">Add another supplier</button></div></main>
  return <main className="min-h-screen bg-medzo-light-bg px-4 py-8 sm:px-6 sm:py-10"><div className="mx-auto max-w-4xl"><h1 className="text-2xl font-bold text-[#0a192f] sm:text-3xl">Add supplier</h1><p className="mb-6 mt-2 text-medzo-text-light">Enter the supplier's contact and business details.</p>{error && <p role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</p>}{duplicate && <div role="alert" className="mb-4 rounded-xl border border-amber-300 bg-amber-50 p-5 text-amber-900"><h2 className="font-bold">Potential duplicate supplier</h2><p className="mt-1">A supplier with the same name or email already exists. Review the details before saving another record.</p><div className="mt-4 flex gap-3"><button onClick={() => save(duplicate, true)} disabled={busy} className="rounded-lg bg-amber-700 px-5 py-2.5 font-semibold text-white disabled:opacity-60">{busy ? 'Saving...' : 'Save duplicate anyway'}</button><button onClick={() => setDuplicate(null)} className="rounded-lg border border-amber-400 px-5 py-2.5 font-semibold">Review form</button></div></div>}<SupplierForm onSubmit={save} onChange={() => setDuplicate(null)} busy={busy} /></div></main>
}
