import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import SupplierForm from '../components/SupplierForm'
import { deactivateSupplier, getSupplier, updateSupplier } from '../api/suppliersApi'

export default function EditSupplierPage() {
  const { supplierId } = useParams()
  const [supplier, setSupplier] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  useEffect(() => { getSupplier(supplierId).then(setSupplier).catch((requestError) => setError(requestError.message || 'Supplier details could not be loaded.')) }, [supplierId])
  const save = async (values) => { setBusy(true); setError(''); try { setSupplier(await updateSupplier(supplierId, values)); setSaved(true) } catch (requestError) { setError(requestError.message || 'Supplier details could not be saved.') } finally { setBusy(false) } }
  const deactivate = async () => { if (!window.confirm(`Deactivate ${supplier.name}? This supplier will no longer be available for new purchase orders.`)) return; setBusy(true); setError(''); try { await deactivateSupplier(supplierId); setSupplier(current => ({ ...current, isActive: false })); setSaved(false) } catch (requestError) { setError(requestError.message || 'Supplier could not be deactivated.') } finally { setBusy(false) } }
  if (error && !supplier) return <main className="min-h-screen bg-medzo-light-bg p-8"><p role="alert" className="mx-auto max-w-4xl rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</p></main>
  if (!supplier) return <main className="min-h-screen bg-medzo-light-bg p-8 text-center text-medzo-text-light">Loading supplier…</main>
  return <main className="min-h-screen bg-medzo-light-bg px-4 py-8 sm:px-6 sm:py-10"><div className="mx-auto max-w-4xl"><Link to="/suppliers" className="text-sm font-semibold text-medzo-blue hover:underline">← Back to suppliers</Link><div className="mb-6 mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-[#0a192f] sm:text-3xl">Edit supplier</h1><p className="mt-2 text-medzo-text-light">Update supplier details or deactivate this record.</p></div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${supplier.isActive ? 'bg-green-100 text-green-800' : 'bg-slate-200 text-slate-700'}`}>{supplier.isActive ? 'Active' : 'Inactive'}</span></div>{error && <p role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</p>}{saved && <p role="status" className="mb-4 rounded-lg border border-green-200 bg-green-50 p-4 text-green-800">Supplier details updated successfully.</p>}<SupplierForm initial={supplier} onSubmit={save} busy={busy} submitLabel="Save changes" />{supplier.isActive && <section className="mt-6 rounded-2xl border border-red-200 bg-white p-6"><h2 className="text-lg font-bold text-[#0a192f]">Deactivate supplier</h2><p className="mt-1 text-sm text-medzo-text-light">This preserves the supplier record for historical purchase orders but prevents it being used for new ones.</p><button type="button" onClick={deactivate} disabled={busy} className="mt-4 rounded-lg bg-red-700 px-5 py-2.5 font-semibold text-white disabled:opacity-60">Deactivate supplier</button></section>}</div></main>
}
