import { useState } from 'react'
import { validateStockBatch } from '../validation/stockBatchValidation'

const empty = { medicineId: '', batchNumber: '', description: '', expiryDate: '', quantity: '', sourceReference: '' }
const minimumExpiryDate = new Date(new Date().setDate(new Date().getDate() + 1)).toISOString().slice(0, 10)
export default function StockBatchForm({ medicines, onSubmit, busy }) {
  const [v, setV] = useState(empty); const [errors, setErrors] = useState({})
  const change = ({ target: { name, value } }) => { setV(x => ({ ...x, [name]: value })); setErrors(x => ({ ...x, [name]: '' })) }
  const submit = async event => { event.preventDefault(); const next = validateStockBatch(v); setErrors(next); if (Object.keys(next).length) return; if (await onSubmit({ ...v, batchNumber: v.batchNumber.trim(), description: v.description.trim() || null, sourceReference: v.sourceReference.trim() || null, quantity: Number(v.quantity) })) setV(empty) }
  const error = name => errors[name] && <span role="alert" className="mt-1 block text-xs text-red-500">{errors[name]}</span>
  return <form onSubmit={submit} noValidate className="rounded-2xl bg-white p-7 shadow-sm"><div className="grid gap-5 sm:grid-cols-2">
    <label className="text-sm font-semibold">Medicine<select name="medicineId" value={v.medicineId} onChange={change} aria-invalid={Boolean(errors.medicineId)} className="mt-1 w-full rounded-lg border border-slate-200 p-3 focus:ring-2 focus:ring-medzo-blue"><option value="">Select medicine</option>{medicines.map(x => <option value={x.id} key={x.id}>{x.name}</option>)}</select>{error('medicineId')}</label>
    <label className="text-sm font-semibold">Batch number<input name="batchNumber" maxLength="100" value={v.batchNumber} onChange={change} aria-invalid={Boolean(errors.batchNumber)} className="mt-1 w-full rounded-lg border border-slate-200 bg-[#f8fafc] p-3 focus:ring-2 focus:ring-medzo-blue" />{error('batchNumber')}</label>
    <label className="text-sm font-semibold sm:col-span-2">Description <span className="font-normal text-slate-500">(optional)</span><textarea name="description" maxLength="500" rows="3" value={v.description} onChange={change} aria-invalid={Boolean(errors.description)} placeholder="Source, pack size, supplier, or other traceability details" className="mt-1 w-full rounded-lg border border-slate-200 bg-[#f8fafc] p-3 focus:ring-2 focus:ring-medzo-blue" />{error('description')}</label>
    <label className="text-sm font-semibold">Expiry date<input name="expiryDate" type="date" min={minimumExpiryDate} value={v.expiryDate} onChange={change} aria-invalid={Boolean(errors.expiryDate)} className="mt-1 w-full rounded-lg border border-slate-200 bg-[#f8fafc] p-3 focus:ring-2 focus:ring-medzo-blue" />{error('expiryDate')}</label>
    <label className="text-sm font-semibold">Quantity<input name="quantity" type="number" min="1" step="1" value={v.quantity} onChange={change} aria-invalid={Boolean(errors.quantity)} className="mt-1 w-full rounded-lg border border-slate-200 bg-[#f8fafc] p-3 focus:ring-2 focus:ring-medzo-blue" />{error('quantity')}</label>
    <label className="text-sm font-semibold sm:col-span-2">Source reference <span className="font-normal text-slate-500">(optional)</span><input name="sourceReference" maxLength="150" value={v.sourceReference} onChange={change} aria-invalid={Boolean(errors.sourceReference)} placeholder="Purchase order, invoice, or delivery reference" className="mt-1 w-full rounded-lg border border-slate-200 bg-[#f8fafc] p-3 focus:ring-2 focus:ring-medzo-blue" />{error('sourceReference')}</label>
  </div>{!medicines.length && <p role="status" className="mt-5 text-sm text-amber-700">Add an active medicine before recording a stock batch.</p>}<button disabled={busy || !medicines.length} className="gradient-btn mt-6 w-full rounded-lg px-6 py-3 font-bold text-white transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-60 sm:w-auto">{busy ? 'Recording…' : 'Record stock batch'}</button></form>
}

