
import { Link } from 'react-router-dom'
import { HeartHandshake, ShieldCheck, Sparkles, Users } from 'lucide-react'

const values = [
  { icon: ShieldCheck, title: 'Safety first', text: 'Accurate catalogue, batch, expiry, and stock records support responsible pharmacy decisions.' },
  { icon: HeartHandshake, title: 'Care with respect', text: 'We make every interaction clear, welcoming, and focused on the person behind the prescription.' },
  { icon: Sparkles, title: 'Reliable information', text: 'Automated stock updates reduce manual mistakes and help our team provide dependable answers.' },
  { icon: Users, title: 'One connected team', text: 'Pharmacists, inventory managers, and administrators work through secure, role-based workflows.' },
]

export default function AboutUs() {
  return <main className="bg-white"><section className="overflow-hidden bg-medzo-light-bg px-4 py-16 sm:px-6 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-medzo-green">About Medzo</p><h1 className="mt-3 text-3xl font-bold leading-tight text-[#0a192f] sm:text-5xl">Better pharmacy care starts with trust and accurate information.</h1><p className="mt-6 text-lg leading-8 text-medzo-text-light">Medzo Pharmacy is committed to providing quality medical products and trusted service for everyone, making each healthcare journey safer, easier, and more convenient.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/products" className="gradient-btn rounded-lg px-6 py-3 text-center font-bold text-white">View products</Link><Link to="/contact" className="rounded-lg border border-medzo-blue bg-white px-6 py-3 text-center font-bold text-medzo-blue">Contact us</Link></div></div><div className="rounded-3xl bg-[#0a192f] p-8 text-white shadow-xl sm:p-10"><p className="text-sm font-bold uppercase tracking-widest text-medzo-green">Our purpose</p><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Make pharmacy care easier to understand and easier to access.</h2><p className="mt-5 leading-7 text-slate-300">Our digital platform keeps staff aligned around medicines, stock movements, and customer needs while protecting operational functions behind secure access.</p><div className="mt-8 grid grid-cols-2 gap-4"><div className="rounded-xl bg-white/10 p-4"><p className="text-2xl font-bold text-medzo-green">Live</p><p className="mt-1 text-sm text-slate-300">stock visibility</p></div><div className="rounded-xl bg-white/10 p-4"><p className="text-2xl font-bold text-medzo-green">Secure</p><p className="mt-1 text-sm text-slate-300">role-based access</p></div></div></div></div></section><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-medzo-green">What guides us</p><h2 className="mt-3 text-3xl font-bold text-[#0a192f]">Care you can count on</h2></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-slate-100 p-6 shadow-sm"><Icon className="text-medzo-blue" aria-hidden="true" /><h3 className="mt-4 text-xl font-bold text-[#0a192f]">{title}</h3><p className="mt-2 leading-7 text-medzo-text-light">{text}</p></article>)}</div></section></main>
}
